📖 DOC: Update Readme
module-federation/node pull request #6
Opened 2022-09-18 18:04 UTC by meerhamzadev

Improve README 
✅ Add a banner image
✅ Add stat badges
✅ Add contributors section
✅ Beautify overall readme

2022-09-20 22:45 UTC, ScriptedAlchemy commented on README.md
> +  <img src="https://img.shields.io/npm/dt/?<package-name>?color=%2317BCB8" alt="downloads">
package name is wrong here

2022-09-20 22:45 UTC, ScriptedAlchemy commented on README.md
> +  <img src="https://img.shields.io/npm/v/<package-name>" alt="version" >
package name is wrong here

2022-09-20 22:45 UTC, ScriptedAlchemy requested changes
see comments

2022-09-20 22:46 UTC, ScriptedAlchemy commented on README.md
> +- Exposes two Webpack Plugins to enable Module Federation.
also check the recent merged, we added UniversalFederationPlugin which wraps both node federation and normal module federation into one plugin for client and server

2022-09-22 04:11 UTC, meerhamzadev commented on README.md
> +  <img src="https://img.shields.io/npm/v/<package-name>" alt="version" >
Actually, I didn't know the package name that's why I add it as a placeholder.

2022-09-24 11:44 UTC, meerhamzadev commented on README.md
> +- Exposes two Webpack Plugins to enable Module Federation.
ok, I will fix all this, tomorrow. Can you please mention the package name?

2022-09-27 10:12 UTC, closed without merging